In [5]:
pip install pandas


  Using cached pandas-1.5.3-cp311-cp311-win_amd64.whl (10.3 MB)
  Using cached pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
  Using cached numpy-1.24.2-cp311-cp311-win_amd64.whl (14.8 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:

pip install scikit-learn

  Using cached scikit_learn-1.2.2-cp311-cp311-win_amd64.whl (8.3 MB)
  Using cached scipy-1.10.1-cp311-cp311-win_amd64.whl (42.2 MB)
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import pandas as pd

In [8]:
data = pd.read_csv('DataSet.csv')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189232 entries, 0 to 189231
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0    Rainfall     189232 non-null  float64
 1    Temperature  189232 non-null  float64
 2    Ph           189232 non-null  float64
 3   Crop          189232 non-null  object 
 4    Production   189232 non-null  float64
dtypes: float64(4), object(1)
memory usage: 7.2+ MB


In [10]:
data = data.drop([' Production'],axis=1)

# no missing data 

In [11]:
data = data[:15000]

In [12]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

Crop = le.fit_transform(data.Crop) 

testing = data 

testing['Crop'] = Crop

In [13]:
testing

Rainfall   Temperature   Ph  Crop
0      400.15082      20.00000  3.0     0
1      400.16331      20.00000  3.2     0
2      400.16387      20.00000  3.2     0
3      400.17967      20.00000  3.2     0
4      400.19582      20.00000  3.2     0
...          ...           ...  ...   ...
14995  534.80315      27.25333  5.3    11
14996  534.85475      27.28333  5.3    11
14997  534.87179      27.31333  5.3    11
14998  534.87179      27.34333  5.3    11
14999  534.91071      27.37333  5.3    11

[15000 rows x 4 columns]

In [15]:
#from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
predictors = data.drop("Crop",axis=1)
target = data["Crop"]

X_train,X_test,Y_train,Y_test = train_test_split(predictors,target,test_size=0.20,random_state=0)

In [16]:
from sklearn import svm

sv = svm.SVC(kernel='linear')

sv.fit(X_train, Y_train)

Y_pred_svm = sv.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score
score_svm = round(accuracy_score(Y_pred_svm,Y_test)*100,2)

print("The accuracy score achieved using Linear SVM is: "+str(score_svm)+" %")

The accuracy score achieved using Linear SVM is: 99.6 %


In [18]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test, Y_pred_svm))

[[1010    0    0    0    0    0    0    0    0    0    0    0]
 [   0  623    0    0    0    0    0    0    0    0    0    0]
 [   0    0  819    0    0    0    0    0    0    0    0    0]
 [   2    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0  198    0    0    0    0    0    0    0]
 [   0    0    0    0    0   20    0    0    0    0    0    0]
 [   1    1    0    0    0    0    1    0    0    0    0    0]
 [   0    0    0    0    0    0    0   60    0    0    0    0]
 [   4    0    0    0    0    0    0    0    2    0    0    0]
 [   0    0    0    0    2    0    0    0    0   54    0    0]
 [   0    0    2    0    0    0    0    0    0    0    2    0]
 [   0    0    0    0    0    0    0    0    0    0    0  199]]


In [19]:
data1 = pd.read_csv('DataSet.csv')
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

Crop = le.fit_transform(data1.Crop) 

testing1 = data1 

testing1['Crop'] = Crop

In [21]:
#from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split
from sklearn.metrics import r2_score

In [23]:
#from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
predictors = testing1.drop(" Production",axis=1)
target = testing1[" Production"]

X_train,X_test,Y_train,Y_test = train_test_split(predictors,target,test_size=0.20,random_state=0)

In [25]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,Y_train)
  
# prediction
y_pred=reg.predict(X_test)
y_pred

array([ 3.77057713,  3.7254756 , -1.38801716, ...,  3.49916032,
        0.19772131, 12.22066847])

In [26]:
# regression Coefficients
#print('\nCoefficients: ', reg.coef_,'\n')

# R-squared score
print('\nR-squared score: ', r2_score(Y_test,y_pred),'\n')


R-squared score:  0.12165023672792807 

